[gdb] Run indent-shell
Run the indent-shell hook to re-indent the shell scripts.

diff --git a/gdb/gcore-1.in b/gdb/gcore-1.in
--- a/gdb/gcore-1.in
+++ b/gdb/gcore-1.in
@@ -131,30 +131,30 @@ fi
 binary_path=$(dirname "$0")
 
 if test "$binary_path" = . ; then
-  # We got "." back as a path.  This means the user executed
-  # the gcore script locally (i.e. ./gcore) or called the
-  # script via a shell interpreter (i.e. sh gcore).
-  binary_basename=$(basename "$0")
+    # We got "." back as a path.  This means the user executed
+    # the gcore script locally (i.e. ./gcore) or called the
+    # script via a shell interpreter (i.e. sh gcore).
+    binary_basename=$(basename "$0")
 
-  # If the gcore script was called like "sh gcore" and the script
-  # lives in the current directory, "which" will not give us "gcore".
-  # So first we check if the script is in the current directory
-  # before using the output of "which".
-  if test -f "$binary_basename" ; then
-    # We have a local gcore script in ".".  This covers the case of
-    # doing "./gcore" or "sh gcore".
-    binary_path="."
-  else
-    # The gcore script was not found in ".", which means the script
-    # was called from somewhere else in $PATH by "sh gcore".
-    # Extract the correct path now.
-    binary_path_from_env=$(which "$0")
-    binary_path=$(dirname "$binary_path_from_env")
-  fi
+    # If the gcore script was called like "sh gcore" and the script
+    # lives in the current directory, "which" will not give us "gcore".
+    # So first we check if the script is in the current directory
+    # before using the output of "which".
+    if test -f "$binary_basename" ; then
+	# We have a local gcore script in ".".  This covers the case of
+	# doing "./gcore" or "sh gcore".
+	binary_path="."
+    else
+	# The gcore script was not found in ".", which means the script
+	# was called from somewhere else in $PATH by "sh gcore".
+	# Extract the correct path now.
+	binary_path_from_env=$(which "$0")
+	binary_path=$(dirname "$binary_path_from_env")
+    fi
 fi
 
 if [ -z "$gdb_binary" ]; then
-   gdb_binary="$binary_path/@GDB_TRANSFORM_NAME@"
+    gdb_binary="$binary_path/@GDB_TRANSFORM_NAME@"
 fi
 
 gdb_binary_basename=$(basename "$gdb_binary")
@@ -162,8 +162,8 @@ gdb_binary_basename=$(basename "$gdb_binary")
 # Check if the GDB binary is in the expected path.  If not, just
 # quit with a message.
 if [ ! -f "$gdb_binary" ]; then
-  echo "gcore: GDB binary ($gdb_binary) not found"
-  exit 1
+    echo "gcore: GDB binary ($gdb_binary) not found"
+    exit 1
 fi
 
 # Initialise return code.
@@ -172,23 +172,23 @@ rc=0
 # Loop through pids
 for pid in "$@"
 do
-	# `</dev/null' to avoid touching interactive terminal if it is
-	# available but not accessible as GDB would get stopped on SIGTTIN.
-	"$gdb_binary" </dev/null \
-	    ${data_directory:+--data-directory "$data_directory"} \
-	    --nx --batch --readnever -iex 'set debuginfod enabled off' \
-	    -ex "set pagination off" -ex "set height 0" -ex "set width 0" \
-	    ${use_coredump_filter:+-ex "set use-coredump-filter ${use_coredump_filter}"} \
-	    ${dump_excluded_mappings:+-ex "set dump-excluded-mappings ${dump_excluded_mappings}"} \
-	    -ex "attach $pid" -ex "gcore $prefix.$pid" -ex detach -ex quit
+    # `</dev/null' to avoid touching interactive terminal if it is
+    # available but not accessible as GDB would get stopped on SIGTTIN.
+    "$gdb_binary" </dev/null \
+		  ${data_directory:+--data-directory "$data_directory"} \
+		  --nx --batch --readnever -iex 'set debuginfod enabled off' \
+		  -ex "set pagination off" -ex "set height 0" -ex "set width 0" \
+		  ${use_coredump_filter:+-ex "set use-coredump-filter ${use_coredump_filter}"} \
+		  ${dump_excluded_mappings:+-ex "set dump-excluded-mappings ${dump_excluded_mappings}"} \
+		  -ex "attach $pid" -ex "gcore $prefix.$pid" -ex detach -ex quit
 
-	if [ -r "$prefix.$pid" ] ; then
-	    rc=0
-	else
-	    echo "$gdb_binary_basename: failed to create $prefix.$pid"
-	    rc=1
-	    break
-	fi
+    if [ -r "$prefix.$pid" ] ; then
+	rc=0
+    else
+	echo "$gdb_binary_basename: failed to create $prefix.$pid"
+	rc=1
+	break
+    fi
 
 
 done
